<?php

declare(strict_types=1);

/**
 * @file
 * Primary module hooks for EWP Institutions User Access module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_access().
 */
function ewp_institutions_user_access_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  // If not an instance of 'FieldableEntityInterface' return neutral.
  if (!$entity instanceof FieldableEntityInterface) {
    // This access result is only dependent on the entity:
    return AccessResult::neutral()->addCacheableDependency($entity);
  }

  $access_manager = \Drupal::service('ewp_institutions_user_access.manager');

  return $access_manager->calculate($entity, $operation, $account);
}
