ewp_institutions_user_access.user_access_restriction.*:
  type: config_entity
  label: 'User access restriction'
  mapping:
    id:
      type: machine_name
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: uuid
    restricted_type:
      type: machine_name
      label: 'Entity type to be restricted'
    restricted_bundle:
      type: machine_name
      label: 'Entity bundle to be restricted'
    reference_field:
      type: machine_name
      label: 'Reference field used to calculate restrictions'
    strict_match:
      type: boolean
      label: 'Strict match'
